//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectProdutosBio.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Mensagens {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Mensagens() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProjectProdutosBio.Resources.Mensagens", typeof(Mensagens).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código já existe.
        /// </summary>
        internal static string Validacao_VerificarMensagemDeCampoCodigoJaExistente {
            get {
                return ResourceManager.GetString("Validacao_VerificarMensagemDeCampoCodigoJaExistente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código é um campo obrigatório.
        /// </summary>
        internal static string Validacao_VerificarMensagemDeCampoCodigoProdutoObrigatorio {
            get {
                return ResourceManager.GetString("Validacao_VerificarMensagemDeCampoCodigoProdutoObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalhes é um campo obrigatório.
        /// </summary>
        internal static string Validacao_VerificarMensagemDeCampoDetalhesProdutoObrigatorio {
            get {
                return ResourceManager.GetString("Validacao_VerificarMensagemDeCampoDetalhesProdutoObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fabricante é um campo obrigatório.
        /// </summary>
        internal static string Validacao_VerificarMensagemDeCampoFabricanteProdutoObrigatorio {
            get {
                return ResourceManager.GetString("Validacao_VerificarMensagemDeCampoFabricanteProdutoObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome é um campo obrigatório.
        /// </summary>
        internal static string Validacao_VerificarMensagemDeCampoNomeProdutoObrigatorio {
            get {
                return ResourceManager.GetString("Validacao_VerificarMensagemDeCampoNomeProdutoObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preço é um campo obrigatório.
        /// </summary>
        internal static string Validacao_VerificarMensagemDeCampoPrecoProdutoObrigatorio {
            get {
                return ResourceManager.GetString("Validacao_VerificarMensagemDeCampoPrecoProdutoObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Produto atualizado com sucesso..
        /// </summary>
        internal static string Validacao_VerificarMensagemDeProdutoAlteradoComSucesso {
            get {
                return ResourceManager.GetString("Validacao_VerificarMensagemDeProdutoAlteradoComSucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Produto criado com sucesso..
        /// </summary>
        internal static string Validacao_VerificarMensagemDeProdutoCadastradoComSucesso {
            get {
                return ResourceManager.GetString("Validacao_VerificarMensagemDeProdutoCadastradoComSucesso", resourceCulture);
            }
        }
    }
}
